"use client"
import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "@/components/Navbar";
import Caraousel from "@/components/Caraousel";
import ClientSection from "@/components/ClientSection";
import Features from "@/components/Features";
import StatisticsCountUp from "@/components/StatisticsCountUp";
import TestimonialsSection from "@/components/TestimonialsSection";
import BlogSection from "@/components/BlogSection";
import DemoSection from "@/components/DemoSection";
import Footer from "@/components/Footer";

//<link rel="stylesheet" href="https://rsms.me/inter/inter.css"></link>
//import type { Metadata } from "next";
import { Inter } from "next/font/google";

//const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> {

    }
    <head/>
      <body>
      <ChakraProvider>
        <Navbar/>
        <Caraousel/>
        <ClientSection/> 
        <Features/>
        <StatisticsCountUp/>
        <TestimonialsSection/>
        <BlogSection/>
        <DemoSection/>
        <Footer/>
        {children}
        </ChakraProvider>
      </body>
    </html>
  );
}


